### ISSUE TITLE
Resampler methods return FrameOrSeriesUnion - Need to be more specific when possible

### ISSUE THREAD

**Issue by AchmadFathoni** [pandas-dev/pandas-stubs#181]
**Describe the bug**
 False positive error warning when using iloc function from resampler data frame.

**To Reproduce**
 Using pyright on
```
N = 10
index = pd.date_range("1/1/2000", periods=N, freq="T")
x = [x for x in range(N)]
df = pd.DataFrame({"a": x, "b": x, "c": x}, index=index)
df.resample("2T").last().iloc[1:, :]
```
Produces
```
 error: Argument of type "tuple[slice, slice]" cannot be assigned to parameter "idx" of type "np_ndarray_anyint | Index | slice" in function "__getitem__"
    Type "tuple[slice, slice]" cannot be assigned to type "np_ndarray_anyint | Index | slice"
      "tuple[slice, slice]" is incompatible with "Index"
      "tuple[slice, slice]" is incompatible with "slice"
      "tuple[slice, slice]" is incompatible with "np_ndarray_int8"
      "tuple[slice, slice]" is incompatible with "np_ndarray_int16"
      "tuple[slice, slice]" is incompatible with "np_ndarray_int32"
      "tuple[slice, slice]" is incompatible with "np_ndarray_int64"
      "tuple[slice, slice]" is incompatible with "np_ndarray_uint8" (reportGeneralTypeIssues)

```

**Environment**
 - Arch Linux
 - python 3.10.5
 - pyright 1.1.265
 - pandas-stub 1.4.3.220801

**Comment by Dr-Irv** [comment]
This is going to take some work to fix.  The issue here is that `Resampler.last()` returns `DataFrame | Series`.  To make this work right, there are two possible options to explore:
1) Rewrite `Resampler` to be generic, based on whether it is called by `Series.resample()` or `DataFrame.resample()` .
2) As in `groupby`, create a `DataFrameResampler` and `SeriesResampler` that are pretty much the same, except each method returns `DataFrame` or `Series`, respectively, and change `resample()` in `frame.pyi` and `series.pyi` to return one of those two, respectively.

**Comment by AchmadFathoni** [comment]
Could you give me an example of generic class?

**Comment by Dr-Irv** [comment]
> Could you give me an example of generic class?

See `series.pyi`  .  We declare `Series` to be `Generic`
