### ISSUE TITLE
Is there a way to indicate possibility of missing values in a pandas-stubs type hint for a Series/DataFrame?

### ISSUE THREAD

**Issue by bml1g12** [pandas-dev/pandas-stubs#215]
Is there a way to indicate the possibility of missing values in a pandas-stubs type hint for a Series/DataFrame?

e.g. If we wish to indicate that `input` may contain some missing values amongst this series of Timedeltas?

```
def foo(input: "pd.Series[pd.Timedelta]") --> "pd.Series[pd.Timedelta]":
     return input
```

(Note: I'm also enclosing type hints in quotes because `pylint` doesn't like the pandas-stubs throws an unsubscriptable-object error otherwise)

`isinstance(np.nan, float) is True`, so I was imagining I might be able to do something like:

```
import typing as t
NaN: t.TypeAlias = float
def foo(input: "pd.Series[t.Union[pd.Timedelta, NaN]]") --> "pd.Series[t.Union[pd.Timedelta, NaN]]":
     return input
```
But I can see this is not valid syntax 

Thanks for any help,

**Comment by Dr-Irv** [comment]
Missing values can appear in a `Series` for a variety of reasons at runtime.  So you can't do a static type hint that indicates that missing values might be present.

Type hints are static, and because things can change under the hood due to runtime computations, there is no way to know if a `NaN` will be inside.

**Comment by bml1g12** [comment]
I see thank you

I've noticed the pandera library might be able to do some dynamic type checking for this, so I'll try that instead
