### ISSUE TITLE
Type of "to_sql" is partially unknown

### ISSUE THREAD

**Issue by gertcuykens** [pandas-dev/pandas-stubs#353]
osx vscode strict mode
pip3.10 install -U 'psycopg[c]'
pip3.10 install -U --pre SQLAlchemy
pip3.10 install -U pandas
pip3.10 install -U pandas-stubs

```python
    engine = create_engine(
        "postgresql+psycopg://gert:p@localhost/gert", echo=False, future=True
    )

    with engine.begin() as conn:
        stmt = select(A)
        df = pd.read_sql(stmt, conn)
        with pd.option_context('display.max_rows', None, 'display.max_columns', None):
            print(df)
        df.to_sql('test', conn, if_exists='replace', index = False)
```

Type of "to_sql" is partially unknown

<img width="735" alt="image" src="https://user-images.githubusercontent.com/863731/193730680-2ee21aa3-5381-4bec-8bca-4547060abbeb.png">
<img width="679" alt="image" src="https://user-images.githubusercontent.com/863731/193730874-319c83b3-2e45-405f-be32-42ff598f9fce.png">

**Comment by bashtage** [comment]
PRs welcome to improve missing types.

**Comment by gertcuykens** [comment]
https://github.com/pandas-dev/pandas-stubs/blob/main/pandas-stubs/io/sql.pyi#L103-L118

I assume it has to do with this part right?

Maybe it's just this two lines for it to wrok?
```
index_label: str =...,
chunksize: int=...,
```

**Comment by Dr-Irv** [comment]
I think this is more to do with sqlalchemy types.  If I use strict mode in VS Code on your sample, I get this:
![image](https://user-images.githubusercontent.com/15113894/193820615-fd9271b9-060f-461f-a9b4-a5cb9083ee7c.png)

Doing a `reveal_type(conn)` shows `conn` as being `Unknown`, so then there is no match for `to_sql()`, because `conn` has an unknown type.

After the first `with` statement, if I insert:
```python
        conn = cast(Connectable, conn)
```
then the `to_sql()` statement type checks fine.

If I use basic type checking in VS Code, there is no problem.

Note that on the `create_engine()` statement, I am getting the following message in VS Code:
```text
Type of "create_engine" is partially unknown
  Type of "create_engine" is "Overload[(url: URL | str, *, strategy: Literal['mock'], **kwargs: Unknown) -> MockConnection, (url: URL | str, *, module: Any | None = ..., enable_from_linting: bool = ..., future: Literal[True], **kwargs: Unknown) -> Engine, (url: URL | str, *, module: Any | None = ..., enable_from_linting: bool = ..., future: Literal[False] = ..., **kwargs: Unknown) -> Engine]"
```

**Comment by gertcuykens** [comment]
use this version ```pip3.10 install -U --pre SQLAlchemy```

**Comment by Dr-Irv** [comment]
> use this version `pip3.10 install -U --pre SQLAlchemy` for me everything is fine in strict mode except to_sql

I did do that.  I'm on Windows, so not sure if that makes a difference.  What got installed was 1.4.41.

Can you do a `reveal_type(conn)` and see what VS Code reports?

**Comment by Dr-Irv** [comment]
OK, I now know what is happening here.  The message about being "partially unknown" is because `to_sql()` returns `int | None`.  The result is based on the underlying connector and database and whether it returns the number of rows inserted.   We can't do static typing to determine that.

So you have to do a `cast` here or turn down the typing setting from `strict` to `basic`

**Comment by Dr-Irv** [comment]
Never mind.  It has something to do with this declaration in the stubs:
```python
        method: Literal["multi"]
        | Callable[[SQLTable, Any, list[str], Iterable], int | None]
        | None = ...,
```
If `Iterable` is changed to `Iterable[Any]`, then the message goes away.

PR welcome to change:
https://github.com/pandas-dev/pandas-stubs/blob/cb56bfaa91ec6af978b31cf35a991d346169b264/pandas-stubs/core/generic.pyi#L168

to use `Iterable[Any]` here, Would accept a PR without tests.

**Comment by gandhis1** [comment]
Is it supposed to be `Any`? Isn't it an `Iterable[Tuple[Any]]` or something like that? Could even use `ScalarT` here maybe?

**Comment by Dr-Irv** [comment]
> Is it supposed to be `Any`? Isn't it an `Iterable[Tuple[Any, ...]]` or something like that? Could even use `ScalarT` here maybe, as in `Iterable[Tuple[ScalarT, ...]]`

Not entirely clear from the documentation.  Maybe `Iterable[list[Scalar] | tuple[Scalar]]` is the right thing.  Can't use `Sequence`, because `str` matches `Sequence[str]`

**Comment by gandhis1** [comment]
Here's what appears to be the code: https://github.com/pandas-dev/pandas/blob/e0608cb42e98f165fd99b595b2c9d0bfeb208b8f/pandas/io/sql.py#L948

`data_list` is a `List[NdArray]`, and gets passed to `zip`, so I believe it is indeed a `tuple`

**Comment by Dr-Irv** [comment]
But this code makes it seem like it could be a `list` as well:
https://github.com/pandas-dev/pandas/blob/e0608cb42e98f165fd99b595b2c9d0bfeb208b8f/pandas/io/sql.py#L854

**Comment by gandhis1** [comment]
I believe that code accepts `data_iter`, the `Iterator[Tuple[Any, ...]]` as an input. There is a docstring there, but I believe that docstring is wrong:

```
        data_iter : generator of list
           Each item contains a list of values to be inserted
```

In any case I would need to put together an example to prove this, in the interim it certainly doesn't hurt much to have a slightly broader type

**Comment by gandhis1** [comment]
Here is a code example:

```python
import pandas as pd
import sqlite3


def insert_method(pd_table, conn, keys, data_iter):
    print("pd_table:", type(pd_table))
    print("conn:", type(conn))
    print("keys:", type(keys))
    print("data_iter:", type(data_iter))
    data = list(data_iter)
    print("data_iter:", type(data[0]))

with sqlite3.connect(":memory:") as con:
    df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]})
    df.to_sql("table", con=con, method=insert_method)
```

>pd_table: <class 'pandas.io.sql.SQLiteTable'>
conn: <class 'sqlite3.Cursor'>
keys: <class 'list'>
data_iter: <class 'zip'>
data_iter: <class 'tuple'>

This confirms my thinking above that ultimately a `zip` gets passed, so `data_iter` is always going to have a `tuple` inner element. The harm in accepting `list` is very minimal. The only thing preventing `list` would do is catch if someone was mutated the object with `append()` or otherwise. Like, for instance, this:

```
def insert_method(pd_table, conn, keys, data_iter):
   for row in data_iter:
       row.remove("something")
       # do something with the row
```

Probably not something an insertion method function should do (mutating values), but nevertheless...

**Comment by Dr-Irv** [comment]
> This confirms my thinking above that ultimately a `zip` gets passed, so `data_iter` is always going to have a `tuple` inner element.

Thanks for the test.  I misread the code.  We should just use `Iterable[tuple[Any,...]]`
