### ISSUE TITLE
DatetimeLike annotation does not appear to work with dates

### ISSUE THREAD

**Issue by gandhis1** [pandas-dev/pandas-stubs#369]
This example is `bdate_range`, but I suspect this issue is spread more widely.

```
    import pandas as pd
    from typing import Optional
    from datetime import date
    a: Optional[date] = date(2022, 1, 1)
    b: Optional[date] = date(2022, 1, 10)
    dr = pd.bdate_range(a, b, freq="d")
```

> error: Argument 2 to "bdate_range" has incompatible type "Optional[date]"; expected "Union[str, Union[datetime, datetime64, Timestamp], None]"  [arg-type]

Tagging @bashtage as I think he's done some work around this recently. It seems to me that we may have made an assumption somewhere that `date` is a subset of `datetime` (it's actually the opposite).

**Comment by bashtage** [comment]
The issue was that `date` is not datetime-like in the sense that some pandas functions that lise datetime-like do not accept date.  What is needed is a new type DateAndDatetimeLike that includes DateTimeLike + `date`, but this needs to be thoroughly tested.

**Comment by gandhis1** [comment]
I am actually surprised that some functions don't accept `date`. Do you have any examples? I'm wondering if it's more of an oversight than an actual incompatibility. Or is it just that the docs don't say that it accepts a `date` when it does?

I don't have any hard facts, but I suspect that more of the `pandas` time series API accepts a `date` than doesn't. If you agree with that, can we just revert the change?

**Comment by bashtage** [comment]
It was one of the functions in #351.  I tried all of the datetime-like in the type alias and date raised. Basically, it seem there is no consistent definition of what is "datetime like" in pandas.

We shouldn't revert the change since that will result in too broad static typing.  All functions that take DatetimeLike should be tested wtih date, and if they pass they should use a new type (e.g. DateAndDatetimeLike).

**Comment by bashtage** [comment]
The function was `interval_range`
