### ISSUE TITLE
Nightly build appears to be broken

### ISSUE THREAD

**Issue by gandhis1** [pandas-dev/pandas-stubs#429]

**Comment by Dr-Irv** [comment]
Things to change:
1. In https://github.com/pandas-dev/pandas-stubs/blob/c4397e54a6ede2fbd64d7df0dc5c5112875e118f/tests/test_frame.py#L1302 change the index used from 2 to 1 (due to change in behavior of `nth`)
2. In the following, change `pytest.warns` to use `pytest_warns_bounded`
   -  https://github.com/pandas-dev/pandas-stubs/blob/c4397e54a6ede2fbd64d7df0dc5c5112875e118f/tests/test_indexes.py#L169 
   - https://github.com/pandas-dev/pandas-stubs/blob/c4397e54a6ede2fbd64d7df0dc5c5112875e118f/tests/test_pandas.py#L755
   - https://github.com/pandas-dev/pandas-stubs/blob/c4397e54a6ede2fbd64d7df0dc5c5112875e118f/tests/test_pandas.py#L758
   - https://github.com/pandas-dev/pandas-stubs/blob/c4397e54a6ede2fbd64d7df0dc5c5112875e118f/tests/test_pandas.py#L762
   - https://github.com/pandas-dev/pandas-stubs/blob/c4397e54a6ede2fbd64d7df0dc5c5112875e118f/tests/test_scalars.py#L341
   - https://github.com/pandas-dev/pandas-stubs/blob/c4397e54a6ede2fbd64d7df0dc5c5112875e118f/tests/test_scalars.py#L458
   - https://github.com/pandas-dev/pandas-stubs/blob/c4397e54a6ede2fbd64d7df0dc5c5112875e118f/tests/test_series.py#L263  (and the lines below)
