### ISSUE TITLE
typing_extensions shouldn't be a dependency on Python 3.11+

### ISSUE THREAD

**Issue by paper42** [pandas-dev/pandas-stubs#478]
**Describe the bug**
All of the names imported from typing_extensions are available in the typing module in the standard library on Python 3.11+.

**To Reproduce**
1. for example `python3 -c "from typing import Never"` where python3 is Python 3.11

**Please complete the following information:**
 - OS: Linux
 - OS Version Void Linux rolling
 - python 3.11
 - version of type checker -
 - version of installed `pandas-stubs` master

**Additional context**
Most programs do something similar to this:
```python3
try:
	from typing import Never
except ImportError:
	from typing_extensions import Never
```

**Comment by Dr-Irv** [comment]
We can't use `try..except` in the stubs.

We can test the version number and change the imports based on the version number, but that just increases our maintenance burden.  

It's not clear why the stubs can't just import from `typing_extensions`, since that is something that will work for python 3.8 through 3.11.   Is that causing a problem for you?

**Comment by twoertwein** [comment]
`typing_extensions` is only a development dependency: pip/conda should not install it (if you use mypy, it is already installed)

https://github.com/pandas-dev/pandas-stubs/blob/0c5b0cd65da47dd81382365e35b93f39761910d0/pyproject.toml#L46

When pandas requires at least 3.10, we can use `typing.TypeAlias` and with 3.11 `typing.Never`. Adding `if sys.version_info` just to use different imports without providing a real benefit  (at least, I don't see one) just complicates things.

**Comment by twoertwein** [comment]
@AlexWaygood  `flake8-pyi` recommends using the `collections.abc` imports for pyi files (even for python 3.8). Is there a reason not to do the same for `typing_extensions` (or could that be a new feature for flake8-pyi)?

**Comment by AlexWaygood** [comment]
> @AlexWaygood `flake8-pyi` recommends using the `collections.abc` imports for pyi files (even for python 3.8). Is there a reason not to do the same for `typing_extensions` (or could that be a new feature for flake8-pyi)?

As in, you'd like flake8-pyi to complain if somebody tried importing `Literal` from `typing` instead of `typing_extensions` in a stub file?

**Comment by twoertwein** [comment]
> As in, you'd like flake8-pyi to complain if somebody tried importing `Literal` from `typing` instead of `typing_extensions` in a stub file (for example)?

If there is no reason not to do that, then yes :) But I'm more interested in whether there is a reason not to do that. If there is none, I would be fine simply re-writing all `typing_extensions.{Never,TypeAlias}` in pandas-stubs.

**Comment by AlexWaygood** [comment]
Over at typeshed, we always import `Literal`/`TypeAlias`/`Never`/etc. from `typing_extensions` rather than `typing`. That's because the situation is different to the `collections.abc`/`typing` choice for `Mapping`/`Sequence`/`Iterable`/etc. For the `collections.abc` imports, the _runtime_ behaviour changed in 3.9 — but the runtime behaviour is irrelevant to a stub, so we can just use the newer syntax in a stub. For the `typing_extensions` imports, however, these symbols just don't exist in the `typing` module on Python 3.7 (neither at runtime nor in the stub), so we wouldn't be able to import them from `typing` without breaking compatibility with Python 3.7.

We could plausibly forbid importing `Literal` from `typing`. But that feels maybe a bit too opinionated, even for flake8-pyi 😄 E.g. numpy's stubs only support 3.8+, so it's reasonable for them to import `Literal` from `typing` instead of `typing_extensions`. Which Python versions you want to support has to be decided on a per-project basis.

**Comment by AlexWaygood** [comment]
> I was thinking about the opposite. Similar to numpy, pandas(-stubs) requires 3.8+.

Oh I see! I guess we could plausibly add a lint to forbid importing `Literal` from `typing_extensions`, and just switch it off over at typeshed. But I feel like I'd prefer it if it were the same error code as the other import-linting errors. So that leads me to prefer leaving this until Python 3.7 is EOL and typeshed has dropped support 🙂

**Comment by paper42** [comment]
It is just an unnecessary dependency I noticed, nothing more. I was not aware of the issue with try except block and I get that comparing the python version would be unnecessarily complicated. Thank you and feel free to close this issue.
