### ISSUE TITLE
Cannot access member "contains" for type "ExtensionArray"

### ISSUE THREAD

**Issue by davetapley** [pandas-dev/pandas-stubs#664]
**Describe the bug**

```
Cannot access member "contains" for type "ExtensionArray"
  Member "contains" is unknownPylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
(function) contains: Unknown
```

**To Reproduce**

from https://github.com/pandas-dev/pandas/issues/52616#issuecomment-1506195632:

```py
df = pd.DataFrame({'A': range(1, 10)})
obj = pd.Interval(1,4)
ser = pd.Series(obj, index=df.index)
arr = ser.array
arr.contains(df["A"])
```

**Please complete the following information:**
 - OS: Linux
 - OS Version  Ubuntu 20.04.4 LTS
 - python version 3.10.9
 - version of type checker Pylance v2023.4.40
 - version of installed `pandas-stubs` 2.0.0.230412-py3-none-any

**Comment by twoertwein** [comment]
`ExtensionArray` does not have `contains`. `arr` is in your example of type `IntervalArray` which has `contains` (in pandas and pandas-stubs).

We might be able to have overloads for `def array` based on the generic type: return specific subclasses and fallback to ExtensionArray.

**Comment by Dr-Irv** [comment]
There are a couple of issues here:

1. We are not recognizing that `pd.Series(pd.Interval(1,4))` produces `pd.Series[Interval[int]]`
2. If we have a `Series[Interval[int]]` or `Series[Interval[float]]`, then `Series.array` should return `IntervalArray` rather than `ExtensionArray`

To solve the latter, need to create an overload for `Series.array()`, but I'm not sure that will work with `mypy`, so may need to have a type called `IntervalSeries` that takes care of that.
