### ISSUE TITLE
error: Argument 1 to "astype" of "DataFrame" has incompatible type "Literal['int32[pyarrow]']";

### ISSUE THREAD

**Issue by randolf-scholz** [pandas-dev/pandas-stubs#733]
```python
import pandas as pd

df = pd.DataFrame([1,23])
df = df.astype("int32[pyarrow]")
```

**Please complete the following information:**
- pandas                        2.0.2
- pandas-stubs                  2.0.2.230605

**Additional context**

**Comment by Dr-Irv** [comment]
We have to add the various arrow types to the various `*DtypeArg` type aliases in `pandas-stubs/_typing.pyi`

**Comment by Dr-Irv** [comment]
> Is this really useful?!? Just allow `str`

The reason we have all of these types is so things like `Series.astype("int")` will return `Series[int]`.  Allows us to track the types of series.

Secondly, allowing any `str` would mean that `Series.astype("foobar")` would be accepted, and we don't want to allow that.

**Comment by randolf-scholz** [comment]
Hm, that makes sense, but `astype(str)` should still be allowed as a fallback, in which case `Series[Any]` should be inferred. For example, if the data type is created dynamically (think `dtype="int32[pyarrow]" if pyarrow_available() else "Int32"`).

**Comment by gandhis1** [comment]
The first example you gave, I am pretty sure Mypy correctly interprets it as as a `Literal["int32[pyarrow]", "Int32"]`, in which case I believe it would be accepted.

That said, the other more dynamic examples you mentioned still hold. Ideally there would be a way to say, accept a non-literal `str`, since we have the ability to verify literals.
